"""Regenerate the talk's assets in paper/presentation/assets/.

    uv run --with cairosvg --with playwright python paper/presentation/make_assets.py

Three kinds of asset, all derived rather than drawn by hand:

* ``segments.tex`` --- the reference game's real segment structure (118
  segments, their endpoint colours and the kind of critical move that ends
  each), read back by ``lcfigures.sty``.  The talk's central diagram is
  therefore a picture of the actual game, not a schematic.
* board diagrams --- positions replayed out of ``data/longest.pgn`` and
  rendered to vector PDF, same pipeline as ``paper/figures/make_figures.py``.
* screenshots --- the pages the talk cites, captured headlessly.

Screenshots are third-party material shown for citation; see README.md.
Everything is skipped gracefully if its optional dependency is missing, so
a partial run still leaves a deck that compiles.
"""

from __future__ import annotations

import json
import sys
import urllib.request
from pathlib import Path

import chess
import chess.pgn

HERE = Path(__file__).parent
ASSETS = HERE / "assets"
REPO = HERE.parent.parent
PGN = REPO / "data" / "longest.pgn"

BOARD_SIZE = 320

# The board is tinted to the deck's blue palette (see longchess.sty) so the
# rendered positions sit beside the TikZ diagrams without a colour clash.
# python-chess's default brown board does not.
BOARD_COLORS = {
    "square light": "#E7E7F7",
    "square dark": "#A6A6D8",
    "square light lastmove": "#C9C9F0",
    "square dark lastmove": "#8C8CC8",
    "margin": "#E7E7F7",
    "coord": "#6E6E85",
    "arrow green": "#0E7A4A",
    "arrow blue": "#3333B2",
}
WALL = "#C0000055"      # the home rank the attacker cannot pass
LANE = "#0E7A4A44"      # the file an unresolved origin pair is locked on

# The two videos that started the project, and the pages they led to.
YOUTUBE = {
    "shot-yt-short": "ta6hvZS34ro",
    "shot-yt-video": "198K9TPT7KI",
}
PAGES = {
    "shot-labelle": ("https://wismuth.com/chess/longest-game.html", 1280, 900),
    "shot-augment": ("https://augmentchess.org/", 1280, 900),
}
PDF_FIRST_PAGE = {
    "shot-sigbovik": "http://tom7.org/chess/longest.pdf",
}


# --------------------------------------------------------------- segments
def segments(game: chess.pgn.Game) -> list[dict]:
    """Cut the game at its critical moves, exactly as Definition 2.2 does."""
    board = game.board()
    out: list[dict] = []
    start = 0
    ply = 0
    for ply, move in enumerate(game.mainline_moves(), start=1):
        capture = board.is_capture(move)
        pawn = board.piece_type_at(move.from_square) == chess.PAWN
        san = board.san(move)
        board.push(move)
        if capture or pawn:
            out.append(
                {
                    "end": ply,
                    "len": ply - start,
                    "colour": "W" if ply % 2 else "B",
                    "kind": "both" if (capture and pawn) else "cap" if capture else "pawn",
                    "san": san,
                }
            )
            start = ply
    if start < ply:  # the closing quiet segment, T = 1
        out.append(
            {
                "end": ply,
                "len": ply - start,
                "colour": "W" if ply % 2 else "B",
                "kind": "term",
                "san": "#",
            }
        )
    return out


def blocks(segs: list[dict]) -> list[tuple[str, int]]:
    """Run-length encode the endpoint colours: the endpoint pattern."""
    runs: list[list] = []
    for s in segs:
        if runs and runs[-1][0] == s["colour"]:
            runs[-1][1] += 1
        else:
            runs.append([s["colour"], 1])
    return [(c, n) for c, n in runs]


def write_segments_tex(segs: list[dict]) -> None:
    """Emit the data lcfigures.sty draws from.

    \\lcsegdata is a comma list of ``colour/kind`` in segment order, and the
    handful of \\lcseg* scalars are the numbers the captions quote, so that
    text and picture cannot drift apart.
    """
    runs = blocks(segs)
    short = [i + 1 for i, s in enumerate(segs) if s["len"] != 150]
    body = ",".join(f"{s['colour']}/{s['kind']}" for s in segs)
    counts = {k: sum(1 for s in segs if s["kind"] == k) for k in ("pawn", "cap", "both", "term")}
    spans, at = [], 1
    for colour, n in runs:
        spans.append(f"{colour}/{at}/{at + n - 1}/{n}")
        at += n
    lines = [
        f"\\def\\lcsegrunlist{{{','.join(spans)}}}",
        f"\\def\\lcsegnruns{{{len(runs)}}}",
        "% Generated by make_assets.py from data/longest.pgn --- do not edit.",
        "% The reference game of Murphy (SIGBOVIK 2020), verified in Appendix A.",
        f"\\def\\lcsegdata{{{body}}}",
        f"\\def\\lcsegcount{{{len(segs)}}}",
        f"\\def\\lcsegplies{{{segs[-1]['end']}}}",
        f"\\def\\lcsegpattern{{{''.join(c for c, _ in runs)}}}",
        f"\\def\\lcsegruns{{{', '.join(f'{c}{n}' for c, n in runs)}}}",
        f"\\def\\lcsegshort{{{', '.join(str(i) for i in short)}}}",
        f"\\def\\lcsegnshort{{{len(short)}}}",
        f"\\def\\lcsegpawn{{{counts['pawn'] + counts['both']}}}",
        f"\\def\\lcsegcap{{{counts['cap'] + counts['both']}}}",
        f"\\def\\lcsegboth{{{counts['both']}}}",
        f"\\def\\lcsegterm{{{counts['term']}}}",
    ]
    (ASSETS / "segments.tex").write_text("\n".join(lines) + "\n")
    print("segments.tex:", len(segs), "segments,", runs, "short at", short)
    (ASSETS / "segments.json").write_text(json.dumps(segs, indent=1))


# ------------------------------------------------------------------ boards
def write_board(name: str, board: chess.Board, lastmove: chess.Move | None = None,
                arrows: list = (), squares: chess.SquareSet | None = None,
                fill: dict | None = None) -> None:
    try:
        import cairosvg
        import chess.svg
    except ImportError:
        print(f"skip {name}: needs cairosvg (uv run --with cairosvg ...)")
        return
    svg = chess.svg.board(
        board,
        size=BOARD_SIZE,
        coordinates=True,
        lastmove=lastmove,
        arrows=list(arrows),
        squares=squares,
        fill=fill or {},
        colors=BOARD_COLORS,
        borders=False,
    )
    out = ASSETS / f"{name}.pdf"
    cairosvg.svg2pdf(bytestring=svg.encode(), write_to=str(out))
    data = out.read_bytes()
    if data.startswith(b"%PDF-1.7"):
        out.write_bytes(b"%PDF-1.5" + data[8:])
    print(f"{out.name}: {board.fen()}")


def play(san: str, upto: int | None = None) -> tuple[chess.Board, chess.Move]:
    board = chess.Board()
    last = None
    tokens = san.split()
    for token in tokens if upto is None else tokens[:upto]:
        last = board.parse_san(token)
        board.push(last)
    assert last is not None
    return board, last


# The same sequences the paper's figures replay, re-rendered with the talk's
# annotations on top: a wall of pawns, the file a pair is locked on.
CAP10 = ("Nf3 a6 Ng1 a5 Nf3 a4 Ng1 a3 Nxa3 Nc6 Nc4 Rb8 "
         "a3 Nf6 a4 Ng8 a5 Nf6 a6 Ng8 a7 Nf6 a8=Q Ng8")
HOMERANK = "Nf3 e6 Ng1 e5 Nf3 e4 Ng1 e3"


def annotated_boards() -> None:
    import chess.svg

    # The home-rank lemma: Black's pawn has spent its four ranks and stops.
    # The wall is White's home rank; the two arrows are exactly the moves
    # (R1) and (R2) forbid.
    board, last = play(HOMERANK)
    write_board(
        "board-homerank", board, last,
        fill={sq: WALL for sq in chess.SquareSet(chess.BB_RANK_2)},
        arrows=[chess.svg.Arrow(chess.E3, chess.E2, color="#C00000"),
                chess.svg.Arrow(chess.E3, chess.D2, color="#C00000"),
                chess.svg.Arrow(chess.E3, chess.F2, color="#C00000")],
    )

    # The unresolved origin pair, before and after: ten pawn moves, never a
    # diagonal one, so the a-file is never resolved.
    lane = {sq: LANE for sq in chess.SquareSet(chess.BB_FILE_A)}
    board, last = play(CAP10, upto=8)
    write_board("board-cap10a", board, last, fill=lane)
    board, last = play(CAP10)
    write_board("board-cap10b", board, last, fill=lane)

    # The reference game's last position: mate with the clock at 150.
    write_board("board-witness", chess.Board("3k4/3Q4/4K3/8/8/8/8/8 b - - 150 8849"))


def boards(game: chess.pgn.Game) -> None:
    write_board("board-start", chess.Board())
    annotated_boards()

    # The position after the game's last pawn move: sixteen pawns have made
    # ninety-six moves and every one of them has promoted.  This is what
    # Theorem 3.4's equality case looks like on a board.
    board = game.board()
    last_pawn_ply, last_pawn_fen, last_pawn_move = 0, None, None
    for ply, move in enumerate(game.mainline_moves(), start=1):
        pawn = board.piece_type_at(move.from_square) == chess.PAWN
        board.push(move)
        if pawn:
            last_pawn_ply, last_pawn_fen, last_pawn_move = ply, board.fen(), move
    print(f"last pawn move at ply {last_pawn_ply}")
    write_board("board-nopawns", chess.Board(last_pawn_fen), last_pawn_move)

    # King against king: the dead position that costs the 30th capture its
    # closing segment (Lemma 3.5).
    write_board("board-barekings", chess.Board("4k3/8/8/8/8/8/8/4K3 w - - 0 1"))


# ------------------------------------------------------------- screenshots
def screenshots() -> None:
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        print("skip screenshots: needs playwright (uv run --with playwright ...)")
        return
    with sync_playwright() as p:
        browser = p.chromium.launch()
        for name, (url, w, h) in PAGES.items():
            try:
                page = browser.new_page(viewport={"width": w, "height": h},
                                        device_scale_factor=2)
                page.goto(url, wait_until="networkidle", timeout=45000)
                page.screenshot(path=ASSETS / f"{name}.png")
                print(f"{name}.png: {url}")
                page.close()
            except Exception as exc:  # a talk asset is never worth failing over
                print(f"skip {name}: {exc}")
        browser.close()


def thumbnails() -> None:
    for name, vid in YOUTUBE.items():
        for quality in ("maxresdefault", "hqdefault"):
            url = f"https://img.youtube.com/vi/{vid}/{quality}.jpg"
            try:
                with urllib.request.urlopen(url, timeout=30) as r:
                    data = r.read()
                if len(data) > 2000:
                    (ASSETS / f"{name}.jpg").write_bytes(data)
                    print(f"{name}.jpg: {url} ({len(data)} bytes)")
                    break
            except Exception as exc:
                print(f"  {url}: {exc}")


def pdf_first_pages() -> None:
    try:
        import pymupdf
    except ImportError:
        print("skip pdf covers: needs pymupdf (uv run --with pymupdf ...)")
        return
    for name, url in PDF_FIRST_PAGE.items():
        try:
            with urllib.request.urlopen(url, timeout=45) as r:
                raw = r.read()
            doc = pymupdf.open(stream=raw, filetype="pdf")
            doc[0].get_pixmap(dpi=150).save(ASSETS / f"{name}.png")
            print(f"{name}.png: {url}")
        except Exception as exc:
            print(f"skip {name}: {exc}")


def main() -> None:
    ASSETS.mkdir(exist_ok=True)
    game = chess.pgn.read_game(PGN.open())
    if game is None:
        sys.exit(f"could not read {PGN}")
    segs = segments(game)
    write_segments_tex(segs)
    boards(game)
    if "--no-net" not in sys.argv:
        screenshots()
        thumbnails()
        pdf_first_pages()


if __name__ == "__main__":
    main()
